Models/Pokemon.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonAdminApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        public int Id { get; set; }
        public string Navn { get; set; }
        public string Beskrivelse { get; set; }
        public string BildeSrc { get; set; }
        public Nullable<int> TrenerId { get; set; }
    
        public virtual Trener Trener { get; set; }
    }
}

Models/PokemonORM.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonAdminApp2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PokemonDBEntities : DbContext
    {
        public PokemonDBEntities()
            : base("name=PokemonDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pokemon> Pokemons { get; set; }
        public virtual DbSet<Trener> Treners { get; set; }
    }
}

Models/PokemonORM.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Hannah\Documents\WebProsjekt\PokemonAdminApp2\PokemonAdminApp2\Models\PokemonORM.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Models/PokemonORM.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


Models/Trener.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonAdminApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trener
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trener()
        {
            this.Pokemons = new HashSet<Pokemon>();
        }
    
        public int Id { get; set; }
        public string Navn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pokemon> Pokemons { get; set; }
    }
}

Controllers/PokemonAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PokemonAdminApp2.Models;
using System.IO;

namespace PokemonAdminApp2.Controllers
{
    public class PokemonAdminController : Controller
    {
        // GET: PokemonAdmin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult VisAllePokemoner()
        {
            //Koble mot database
            using (var pokemonDBKobling = new PokemonDBEntities())
            {
                //LINQ-spørring (dynamisk variabel)
                var pokemonliste = (from pokemon in pokemonDBKobling.Pokemon.Include("Trener")
                                    select pokemon).ToList();

                return View(pokemonliste);
            }
        }

        [HttpGet]
        public ActionResult OpprettPokemon()
        {
            return View();
        }

        [HttpPost]
        public ActionResult OpprettPokemon(Pokemon pokemon, HttpPostedFileBase file)
        {
            var filnavn = Path.GetFileName(file.FileName);
            var filsti = Path.Combine(Server.MapPath("~/Content"), filnavn);

            file.SaveAs(filsti);

            //Hver gang man kobler til databasen utfører man try-catch-blokk
            try { 
                using (var pokemonDBKobling = new PokemonDBEntities())
                {
                        pokemon.BildeSrc = filnavn;

                        pokemonDBKobling.Pokemon.Add(pokemon);
                        pokemonDBKobling.SaveChanges();

                        return RedirectToAction("VisAllePokemoner");
                }
            }
            catch
            {
                ViewBag.Feilmelding = "Noe gikk galt med databasen.";
                return View();
            }
        }
    }
}

Views/PokemonAdmin/Index.cshtml

@{
    ViewBag.Title = "Index";
}

<h2>Velkommen!</h2>


Views/PokemonAdmin/OpprettPokemon.cshtml
@model PokemonAdminApp2.Models.Pokemon
@{
    ViewBag.Title = "OpprettPokemon";
}

<h2>Opprett Pokemon</h2>

@using (Html.BeginForm("OpprettPokemon", "PokemonAdmin", FormMethod.Post, new { entype = "multipart/form-data"}))
{
    <label>Navn</label>
    @Html.TextBoxFor(pokemon => pokemon.Navn)

    <input type="file" id="file" name="file" />

    <input type="submit" value="Lagre Pokemon" />
}




Views/PokemonAdmin/VisAllePokemoner.cshtml

@model IEnumerable<PokemonAdminApp2.Models.Pokemon>
@{
    ViewBag.Title = "VisAllePokemoner";
}

<h2>Pokemoner</h2>
@foreach (var pokemon in Model)
{
    <article>
        <h3>@pokemon.Navn</h3>
        <p>@pokemon.Beskrivelse</p>
        @if (pokemon.Trener != null){
            <p>Trener: @pokemon.Trener.Navn</p>
        }
 
        <img src="~/Content/@pokemon.BildeSrc" />
    </article>
}

Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>

        <header>
            <h1>PokemonAdmin</h1>
        </header>

        <nav>
            <ul>
                <li>@Html.ActionLink("Hjem", "Index", "PokemonAdmin")</li>
                <li>@Html.ActionLink("Vis Alle", "VisAllePokemoner", "PokemonAdmin")</li>
                <li>@Html.ActionLink("Opprett", "OpprettPokemon", "PokemonAdmin")</li>
            </ul>
        </nav>

        @RenderBody()
    </div>
</body>
</html>